#!/bin/sh 

files="*.cabal *.hs src"
exclude="(\.#.*|flymake).hs$"

do_build() {
  cabal build;
}

cabal configure && do_build

while $(inotifywait -qq -r --exclude $exclude -e modify -e create -e move $files) ; do
  do_build
done;
